//! Markdown schema documentation renderer for BigQuery datasets.
//! Used by the `bq-doc` CLI subcommand — the client-facing demo artifact.

use crate::adapters::bq_adapter::BqTableSchema;

/// Render a full dataset schema doc as markdown.
/// Plain string building on purpose — no template engine.
pub fn render_dataset_doc(project: &str, dataset: &str, schemas: &[BqTableSchema]) -> String {
    let total_columns: usize = schemas.iter().map(|s| s.columns.len()).sum();
    let mut out = String::new();
    out.push_str(&format!("# Dataset: `{}.{}`\n\n", project, dataset));
    out.push_str(&format!(
        "Generated by openclaw-swarm bq-doc on {}. {} tables, {} columns documented.\n\n",
        chrono::Utc::now().format("%Y-%m-%d"),
        schemas.len(),
        total_columns
    ));

    if schemas.len() > 1 {
        out.push_str("## Tables\n\n");
        out.push_str("| Table | Columns | Rows |\n");
        out.push_str("|-------|---------|------|\n");
        for s in schemas {
            out.push_str(&format!(
                "| {} | {} | {} |\n",
                s.table_id,
                s.columns.len(),
                s.num_rows
            ));
        }
        out.push('\n');
    }

    for s in schemas {
        out.push_str(&format!("## Table: `{}`\n\n", s.table_id));
        if let Some(desc) = &s.description {
            out.push_str(&format!("{}\n\n", desc));
        }
        out.push_str(&format!(
            "Rows: {} | Size: {} bytes | Partitioned on: {} | Clustered on: {}\n\n",
            s.num_rows,
            s.num_bytes,
            s.partition_column.as_deref().unwrap_or("-"),
            if s.clustering_columns.is_empty() {
                "-".to_string()
            } else {
                s.clustering_columns.join(", ")
            }
        ));
        out.push_str("| Column | Type | Mode | Description |\n");
        out.push_str("|--------|------|------|-------------|\n");
        for c in &s.columns {
            out.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                c.name,
                c.data_type,
                c.mode,
                c.description.as_deref().unwrap_or("")
            ));
        }
        out.push('\n');
    }

    out
}

/// Render a markdown changelog between two dataset snapshots.
/// Detects added/removed tables and added/removed/retyped columns.
pub fn render_schema_diff(old: &[BqTableSchema], new: &[BqTableSchema]) -> String {
    use std::collections::BTreeMap;

    let old_map: BTreeMap<&str, &BqTableSchema> =
        old.iter().map(|s| (s.table_id.as_str(), s)).collect();
    let new_map: BTreeMap<&str, &BqTableSchema> =
        new.iter().map(|s| (s.table_id.as_str(), s)).collect();

    let mut out = String::new();
    out.push_str(&format!(
        "# Schema changes ({})\n\n",
        chrono::Utc::now().format("%Y-%m-%d")
    ));
    let mut changes = 0;

    for (id, s) in &new_map {
        if !old_map.contains_key(id) {
            out.push_str(&format!("- Added table `{}` ({} columns)\n", id, s.columns.len()));
            changes += 1;
        }
    }
    for id in old_map.keys() {
        if !new_map.contains_key(id) {
            out.push_str(&format!("- Removed table `{}`\n", id));
            changes += 1;
        }
    }

    for (id, new_s) in &new_map {
        let Some(old_s) = old_map.get(id) else { continue };
        let old_cols: BTreeMap<&str, &crate::adapters::bq_adapter::BqColumn> =
            old_s.columns.iter().map(|c| (c.name.as_str(), c)).collect();
        let new_cols: BTreeMap<&str, &crate::adapters::bq_adapter::BqColumn> =
            new_s.columns.iter().map(|c| (c.name.as_str(), c)).collect();

        let mut table_changes = String::new();
        for (name, c) in &new_cols {
            match old_cols.get(name) {
                None => table_changes
                    .push_str(&format!("- Added column `{}` ({})\n", name, c.data_type)),
                Some(o) => {
                    if o.data_type != c.data_type {
                        table_changes.push_str(&format!(
                            "- `{}`: type {} -> {}\n",
                            name, o.data_type, c.data_type
                        ));
                    }
                    if o.mode != c.mode {
                        table_changes.push_str(&format!(
                            "- `{}`: mode {} -> {}\n",
                            name, o.mode, c.mode
                        ));
                    }
                }
            }
        }
        for name in old_cols.keys() {
            if !new_cols.contains_key(name) {
                table_changes.push_str(&format!("- Removed column `{}`\n", name));
            }
        }

        if !table_changes.is_empty() {
            out.push_str(&format!("\n### Changed table `{}`\n\n{}", id, table_changes));
            changes += 1;
        }
    }

    if changes == 0 {
        out.push_str("No schema changes.\n");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::adapters::bq_adapter::BqColumn;

    #[test]
    fn test_render_contains_tables_and_columns() {
        let schemas = vec![BqTableSchema {
            dataset_id: "austin_311".to_string(),
            table_id: "311_service_requests".to_string(),
            columns: vec![BqColumn {
                name: "unique_key".to_string(),
                data_type: "STRING".to_string(),
                mode: "NULLABLE".to_string(),
                description: Some("Case ID".to_string()),
                is_partitioned: false,
                is_clustered: false,
            }],
            partition_column: None,
            clustering_columns: vec![],
            num_bytes: 1234,
            num_rows: 42,
            last_modified: chrono::Utc::now(),
            description: Some("Service requests".to_string()),
        }];

        let doc = render_dataset_doc("bigquery-public-data", "austin_311", &schemas);

        assert!(doc.contains("# Dataset: `bigquery-public-data.austin_311`"));
        assert!(doc.contains("## Table: `311_service_requests`"));
        assert!(doc.contains("| unique_key | STRING | NULLABLE | Case ID |"));
        assert!(doc.contains("Rows: 42"));
        assert!(doc.contains("1 tables, 1 columns documented"));
        // Single table: no TOC section
        assert!(!doc.contains("## Tables\n"));
    }

    #[test]
    fn test_render_empty_dataset() {
        let doc = render_dataset_doc("p", "empty_ds", &[]);
        assert!(doc.contains("# Dataset: `p.empty_ds`"));
        assert!(doc.contains("0 tables"));
    }

    fn table(id: &str, cols: &[(&str, &str)]) -> BqTableSchema {
        BqTableSchema {
            dataset_id: "ds".to_string(),
            table_id: id.to_string(),
            columns: cols
                .iter()
                .map(|(n, t)| BqColumn {
                    name: n.to_string(),
                    data_type: t.to_string(),
                    mode: "NULLABLE".to_string(),
                    description: None,
                    is_partitioned: false,
                    is_clustered: false,
                })
                .collect(),
            partition_column: None,
            clustering_columns: vec![],
            num_bytes: 0,
            num_rows: 0,
            last_modified: chrono::Utc::now(),
            description: None,
        }
    }

    #[test]
    fn test_diff_no_changes() {
        let old = vec![table("users", &[("id", "STRING")])];
        let new = vec![table("users", &[("id", "STRING")])];
        let diff = render_schema_diff(&old, &new);
        assert!(diff.contains("No schema changes"));
    }

    #[test]
    fn test_diff_added_and_removed_table() {
        let old = vec![table("gone", &[("id", "STRING")])];
        let new = vec![table("fresh", &[("id", "STRING")])];
        let diff = render_schema_diff(&old, &new);
        assert!(diff.contains("- Added table `fresh` (1 columns)"));
        assert!(diff.contains("- Removed table `gone`"));
    }

    #[test]
    fn test_diff_column_changes() {
        let old = vec![table("users", &[("id", "STRING"), ("age", "INTEGER")])];
        let new = vec![table("users", &[("id", "INTEGER"), ("email", "STRING")])];
        let diff = render_schema_diff(&old, &new);
        assert!(diff.contains("- `id`: type STRING -> INTEGER"));
        assert!(diff.contains("- Added column `email` (STRING)"));
        assert!(diff.contains("- Removed column `age`"));
        assert!(diff.contains("### Changed table `users`"));
    }
}
