//! Markdown schema documentation renderer for BigQuery datasets.
//! Used by the `bq-doc` CLI subcommand — the client-facing demo artifact.

use crate::adapters::bq_adapter::BqTableSchema;

/// Render a full dataset schema doc as markdown.
/// Plain string building on purpose — no template engine.
pub fn render_dataset_doc(project: &str, dataset: &str, schemas: &[BqTableSchema]) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Dataset: `{}.{}`\n\n", project, dataset));
    out.push_str(&format!(
        "Generated by openclaw-swarm bq-doc on {}. {} tables.\n\n",
        chrono::Utc::now().format("%Y-%m-%d"),
        schemas.len()
    ));

    for s in schemas {
        out.push_str(&format!("## Table: `{}`\n\n", s.table_id));
        if let Some(desc) = &s.description {
            out.push_str(&format!("{}\n\n", desc));
        }
        out.push_str(&format!(
            "Rows: {} | Size: {} bytes | Partitioned on: {} | Clustered on: {}\n\n",
            s.num_rows,
            s.num_bytes,
            s.partition_column.as_deref().unwrap_or("-"),
            if s.clustering_columns.is_empty() {
                "-".to_string()
            } else {
                s.clustering_columns.join(", ")
            }
        ));
        out.push_str("| Column | Type | Mode | Description |\n");
        out.push_str("|--------|------|------|-------------|\n");
        for c in &s.columns {
            out.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                c.name,
                c.data_type,
                c.mode,
                c.description.as_deref().unwrap_or("")
            ));
        }
        out.push('\n');
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::adapters::bq_adapter::BqColumn;

    #[test]
    fn test_render_contains_tables_and_columns() {
        let schemas = vec![BqTableSchema {
            dataset_id: "austin_311".to_string(),
            table_id: "311_service_requests".to_string(),
            columns: vec![BqColumn {
                name: "unique_key".to_string(),
                data_type: "STRING".to_string(),
                mode: "NULLABLE".to_string(),
                description: Some("Case ID".to_string()),
                is_partitioned: false,
                is_clustered: false,
            }],
            partition_column: None,
            clustering_columns: vec![],
            num_bytes: 1234,
            num_rows: 42,
            last_modified: chrono::Utc::now(),
            description: Some("Service requests".to_string()),
        }];

        let doc = render_dataset_doc("bigquery-public-data", "austin_311", &schemas);

        assert!(doc.contains("# Dataset: `bigquery-public-data.austin_311`"));
        assert!(doc.contains("## Table: `311_service_requests`"));
        assert!(doc.contains("| unique_key | STRING | NULLABLE | Case ID |"));
        assert!(doc.contains("Rows: 42"));
    }

    #[test]
    fn test_render_empty_dataset() {
        let doc = render_dataset_doc("p", "empty_ds", &[]);
        assert!(doc.contains("# Dataset: `p.empty_ds`"));
        assert!(doc.contains("0 tables"));
    }
}
