//! Metadata-based lint checks for BigQuery datasets.
//! All checks run on schema metadata only - zero rows read, zero query cost.

use crate::adapters::bq_adapter::BqTableSchema;

const PARTITION_THRESHOLD_BYTES: i64 = 1_000_000_000; // 1 GB
const CLUSTERING_THRESHOLD_BYTES: i64 = 10_000_000_000; // 10 GB
const STALE_DAYS: i64 = 365;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Severity {
    Warn,
    Info,
}

#[derive(Debug, Clone)]
pub struct LintFinding {
    pub severity: Severity,
    pub table: String,
    pub message: String,
}

/// Run all metadata lint checks over a dataset's schemas.
pub fn lint_schemas(schemas: &[BqTableSchema]) -> Vec<LintFinding> {
    let mut findings = Vec::new();
    let now = chrono::Utc::now();

    for s in schemas {
        let warn = |msg: String| LintFinding {
            severity: Severity::Warn,
            table: s.table_id.clone(),
            message: msg,
        };
        let info = |msg: String| LintFinding {
            severity: Severity::Info,
            table: s.table_id.clone(),
            message: msg,
        };

        if s.columns.is_empty() {
            findings.push(warn("table has no columns (broken view or external table?)".to_string()));
            continue;
        }

        if s.num_bytes > PARTITION_THRESHOLD_BYTES && s.partition_column.is_none() {
            findings.push(warn(format!(
                "{:.1} GB but not partitioned - full scans on every query",
                s.num_bytes as f64 / 1e9
            )));
        }

        if s.num_bytes > CLUSTERING_THRESHOLD_BYTES && s.clustering_columns.is_empty() {
            findings.push(warn(format!(
                "{:.1} GB with no clustering - filtered queries scan more than needed",
                s.num_bytes as f64 / 1e9
            )));
        }

        if s.description.is_none() {
            findings.push(info("no table description".to_string()));
        }

        let documented = s.columns.iter().filter(|c| c.description.is_some()).count();
        let pct = documented * 100 / s.columns.len();
        if pct < 50 {
            findings.push(info(format!(
                "{}% of columns documented ({}/{})",
                pct,
                documented,
                s.columns.len()
            )));
        }

        let age_days = (now - s.last_modified).num_days();
        if age_days > STALE_DAYS {
            findings.push(info(format!(
                "not modified in {} days - candidate for archive/cleanup review",
                age_days
            )));
        }
    }

    findings
}

/// Render lint findings as a markdown report.
pub fn render_lint_report(
    project: &str,
    dataset: &str,
    table_count: usize,
    findings: &[LintFinding],
) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Lint report: `{}.{}`\n\n", project, dataset));
    let warns: Vec<&LintFinding> = findings.iter().filter(|f| f.severity == Severity::Warn).collect();
    let infos: Vec<&LintFinding> = findings.iter().filter(|f| f.severity == Severity::Info).collect();
    out.push_str(&format!(
        "Generated by openclaw-swarm bq-lint on {}. {} tables checked: {} warnings, {} suggestions. Metadata-only - no data rows read.\n\n",
        chrono::Utc::now().format("%Y-%m-%d"),
        table_count,
        warns.len(),
        infos.len()
    ));

    if findings.is_empty() {
        out.push_str("No findings - dataset is in good shape.\n");
        return out;
    }

    if !warns.is_empty() {
        out.push_str("## Warnings\n\n");
        for f in &warns {
            out.push_str(&format!("- `{}`: {}\n", f.table, f.message));
        }
        out.push('\n');
    }
    if !infos.is_empty() {
        out.push_str("## Suggestions\n\n");
        for f in &infos {
            out.push_str(&format!("- `{}`: {}\n", f.table, f.message));
        }
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::adapters::bq_adapter::{BqColumn, BqTableSchema};

    fn table(id: &str, bytes: i64, partition: Option<&str>) -> BqTableSchema {
        BqTableSchema {
            dataset_id: "ds".to_string(),
            table_id: id.to_string(),
            columns: vec![BqColumn {
                name: "id".to_string(),
                data_type: "STRING".to_string(),
                mode: "NULLABLE".to_string(),
                description: None,
                is_partitioned: false,
                is_clustered: false,
            }],
            partition_column: partition.map(|s| s.to_string()),
            clustering_columns: vec![],
            num_bytes: bytes,
            num_rows: 100,
            last_modified: chrono::Utc::now(),
            description: Some("described".to_string()),
        }
    }

    #[test]
    fn test_lint_flags_unpartitioned_big_table() {
        let findings = lint_schemas(&[table("big", 5_000_000_000, None)]);
        assert!(findings.iter().any(|f| f.table == "big"
            && f.severity == Severity::Warn
            && f.message.contains("not partitioned")));
    }

    #[test]
    fn test_lint_ignores_small_or_partitioned_tables() {
        let findings = lint_schemas(&[
            table("small", 1_000_000, None),
            table("parted", 5_000_000_000, Some("created_at")),
        ]);
        assert!(!findings.iter().any(|f| f.message.contains("not partitioned")));
    }

    #[test]
    fn test_lint_flags_missing_descriptions() {
        let mut t = table("bare", 1000, None);
        t.description = None;
        let findings = lint_schemas(&[t]);
        assert!(findings.iter().any(|f| f.table == "bare"
            && f.message.contains("no table description")));
        // column "id" has no description either -> 0% coverage
        assert!(findings.iter().any(|f| f.table == "bare"
            && f.message.contains("0% of columns documented")));
    }

    #[test]
    fn test_lint_flags_stale_and_empty_tables() {
        let mut stale = table("stale", 1000, None);
        stale.last_modified = chrono::Utc::now() - chrono::Duration::days(500);
        let mut empty = table("empty", 0, None);
        empty.columns = vec![];
        let findings = lint_schemas(&[stale, empty]);
        assert!(findings.iter().any(|f| f.table == "stale" && f.message.contains("not modified")));
        assert!(findings.iter().any(|f| f.table == "empty"
            && f.severity == Severity::Warn
            && f.message.contains("no columns")));
    }

    #[test]
    fn test_render_report_groups_by_severity() {
        let findings = lint_schemas(&[table("big", 20_000_000_000, None)]);
        let report = render_lint_report("proj", "ds", 1, &findings);
        assert!(report.contains("# Lint report: `proj.ds`"));
        assert!(report.contains("## Warnings"));
        assert!(report.contains("not partitioned"));
        assert!(report.contains("no clustering"));
    }

    #[test]
    fn test_render_report_clean_dataset() {
        let report = render_lint_report("proj", "ds", 3, &[]);
        assert!(report.contains("No findings"));
    }
}
